name: Test external package compatibility against main and last release

on:
  pull_request:
    paths:
      - ".github/workflows/reusable_tox_run.yml"
      - ".github/workflows/test_external_package_compatibility.yml"
  workflow_call:
    inputs:
      package_to_test:
        required: false
        type: string
        default: "napari/npe2"
      package_to_test_ref:
        required: false
        type: string
        default: "main"
      python_version:
        required: false
        type: string
        default: "3.10"
      platform:
        required: false
        type: string
        default: "ubuntu-latest"
      backend:
        required: false
        type: string
        default: "headless"

jobs:
  test:
    name: Initial test
    uses: ./.github/workflows/reusable_run_tox_test.yml
    strategy:
      matrix:
        include:
          - python: ${{ inputs.python_version }}
            platform: ${{ inputs.platform }}
            backend: ${{ inputs.backend }}
            napari_version: "main"
          - python: ${{ inputs.python_version }}
            platform: ${{ inputs.platform }}
            backend: ${{ inputs.backend }}
            napari_version: "v0.4.19x_test"
    with:
      python_version: ${{ matrix.python }}
      platform: ${{ matrix.platform }}
      qt_backend: ${{ matrix.backend }}
      coverage: no_cov
      package_to_test: ${{ inputs.package_to_test }}
      package_to_test_ref: ${{ inputs.package_to_test_ref }}
      napari_version: ${{ matrix.napari_version }}
