# The Comprehensive test suite, which will be run anytime anything is merged into main.
# See test_pull_request.yml for the tests that will be run
name: Comprehensive Test

on:
  push:
    branches:
      - main
      - "v*x"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COLUMNS: 120

concurrency:
  group: comprehensive-test

jobs:
  manifest:
    name: Check Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install check-manifest
      - name: Check Manifest
        run: check-manifest

  build_wheel:
    name: Build wheel
    uses: ./.github/workflows/resuable_build_wheel.yml

  test:
    name: ${{ matrix.platform }}
    uses: ./.github/workflows/reusable_run_tox_test.yml
    needs: build_wheel
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]
        backend: [pyqt5, pyside2]
        include:
          - python: "3.9"
            platform: macos-latest
            backend: pyqt5
          # test with minimum specified requirements
          - python: "3.8"
            platform: ubuntu-20.04
            backend: pyqt5
            MIN_REQ: 1
          # test without any Qt backends
          - python: "3.8"
            platform: ubuntu-20.04
            backend: headless
          - python: "3.11"
            platform: ubuntu-latest
            backend: pyqt6
            tox_extras: "testing_extra"
          - python: "3.11"
            platform: ubuntu-latest
            backend: pyside6
            tox_extras: "testing_extra"
        exclude:
          - python: "3.11"
            backend: pyside2
    with:
      python_version: ${{ matrix.python }}
      platform: ${{ matrix.platform }}
      qt_backend: ${{ matrix.backend }}
      min_req: ${{ matrix.MIN_REQ }}
      coverage: cov
      toxenv: ${{ matrix.toxenv }}
      tox_extras: ${{ matrix.tox_extras }}

  test_pip_install:
    name: pip install
    uses: ./.github/workflows/reusable_pip_test.yml

  test_examples:
    name: test examples
    uses: ./.github/workflows/reusable_run_tox_test.yml
    needs: build_wheel
    with:
        toxenv: py39-linux-pyside2-examples-cov
        timeout: 60
        python_version: 3.9
        constraints_suffix: _examples
        coverage: cov
