# Our minimal suite of tests that run on each pull request
name: PR Test

on:
  pull_request:
    branches:
      - main
      - "v*x"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

env:
  COLUMNS: 120

jobs:
  manifest:
    # make sure all necessary files will be bundled in the release
    name: Check Manifest
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache-dependency-path: setup.cfg
          cache: 'pip'
      - name: Install Dependencies
        run: pip install --upgrade pip
      - name: Install Napari dev
        run: pip install -e .[build]
      - name: Check Manifest
        run: |
          make typestubs
          make check-manifest

  localization_syntax:
    # make sure all necessary files will be bundled in the release
    name: Check l18n syntax
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Check localization formatting
        run: |
          pip install --upgrade pip semgrep
          # f"..." and f'...' are the same for semgrep
          semgrep --error --lang python --pattern 'trans._(f"...")' napari
          semgrep --error --lang python --pattern 'trans._($X.format(...))' napari

  build_wheel:
    name: Build wheel
    uses: ./.github/workflows/resuable_build_wheel.yml

  test_initial:
    name: Initial test
    uses: ./.github/workflows/reusable_run_tox_test.yml
    needs: build_wheel
    strategy:
      matrix:
        include:
          - python: 3.8
            platform: ubuntu-latest
            backend: pyqt5
          - python: 3.11
            platform: ubuntu-latest
            backend: pyqt6
    with:
      python_version: ${{ matrix.python }}
      platform: ${{ matrix.platform }}
      qt_backend: ${{ matrix.backend }}
      coverage: no_cov

  test:
    name: ${{ matrix.platform }}
    uses: ./.github/workflows/reusable_run_tox_test.yml
    needs: test_initial
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest ]
        python: [ "3.9", "3.10" ]
        backend: [ "pyqt5,pyside2" ]
        coverage: [ cov ]
        include:
          # Windows py38
          - python: 3.8
            platform: windows-latest
            backend: pyqt5,pyside2
            coverage: no_cov
          - python: 3.11
            platform: windows-latest
            backend: pyqt6
            coverage: no_cov
          - python: 3.11
            platform: macos-latest
            backend: pyqt5
            coverage: no_cov
          # minimum specified requirements
          - python: 3.8
            platform: ubuntu-20.04
            backend: pyqt5
            MIN_REQ: 1
            coverage: cov
          # test without any Qt backends
          - python: 3.9
            platform: ubuntu-20.04
            backend: headless
            coverage: no_cov
          - python: 3.11
            platform: ubuntu-latest
            backend: pyqt6,pyside6
            coverage: no_cov

    with:
      python_version: ${{ matrix.python }}
      platform: ${{ matrix.platform }}
      qt_backend: ${{ matrix.backend }}
      min_req: ${{ matrix.MIN_REQ }}
      coverage: ${{ matrix.coverage }}
      toxenv: ${{ matrix.toxenv }}

  coverage_report:
    if: ${{ always() }}
    needs: test
    uses: ./.github/workflows/reusable_coverage_upload.yml

  test_pip_install:
    needs: test_initial
    name: pip install
    uses: ./.github/workflows/reusable_pip_test.yml

  test_examples:
    name: test examples
    uses: ./.github/workflows/reusable_run_tox_test.yml
    needs: test_initial
    with:
        toxenv: py39-linux-pyside2-examples-cov
        timeout: 60
        python_version: 3.9
        constraints_suffix: _examples
        coverage: cov

  build_docs:
    name: build docs
    uses: ./.github/workflows/build_docs.yml
    needs: test_initial
